//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Areas.Messeges {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoxMesseges {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoxMesseges() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain_Areas.Messeges.BoxMesseges", typeof(BoxMesseges).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminhão .
        /// </summary>
        public static string Caminhao {
            get {
                return ResourceManager.GetString("Caminhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Pessoa Fisica.
        /// </summary>
        public static string ClientePessoaFisica {
            get {
                return ResourceManager.GetString("ClientePessoaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Pessoa Juridica.
        /// </summary>
        public static string ClientePessoaJuridica {
            get {
                return ResourceManager.GetString("ClientePessoaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione....
        /// </summary>
        public static string Selecione {
            get {
                return ResourceManager.GetString("Selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilitário.
        /// </summary>
        public static string Utilitario {
            get {
                return ResourceManager.GetString("Utilitario", resourceCulture);
            }
        }
    }
}
